services:
  database:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - '8081:8081'
      - '10250-10255:10250-10255'

  cache:
    image: redis:latest
    ports:
      - '6379:6379'

  chrome:
    image: browserless/chrome:latest
    ports:
      - '3000:3000'
    environment:
      - MAX_CONCURRENT_SESSIONS=10
